2025-01-01 20:05:25,733 - passlib.registry - DEBUG - registered 'bcrypt' handler: <class 'passlib.handlers.bcrypt.bcrypt'>
2025-01-01 20:06:20,768 - passlib.registry - DEBUG - registered 'bcrypt' handler: <class 'passlib.handlers.bcrypt.bcrypt'>
2025-01-01 20:07:03,715 - passlib.registry - DEBUG - registered 'bcrypt' handler: <class 'passlib.handlers.bcrypt.bcrypt'>
2025-01-01 20:07:03,733 - __main__ - ERROR - Database initialization error: Column expression, FROM clause, or other columns clause element expected, got <class '__main__.Faculty'>.
2025-01-01 20:07:03,735 - __main__ - ERROR - Application startup error: Column expression, FROM clause, or other columns clause element expected, got <class '__main__.Faculty'>.
2025-01-01 20:08:41,126 - passlib.registry - DEBUG - registered 'bcrypt' handler: <class 'passlib.handlers.bcrypt.bcrypt'>
2025-01-01 20:08:41,151 - __main__ - ERROR - Database initialization error: Column expression, FROM clause, or other columns clause element expected, got <class '__main__.Faculty'>.
2025-01-01 20:08:41,153 - __main__ - ERROR - Application startup error: Column expression, FROM clause, or other columns clause element expected, got <class '__main__.Faculty'>.
2025-01-01 20:09:02,149 - passlib.registry - DEBUG - registered 'bcrypt' handler: <class 'passlib.handlers.bcrypt.bcrypt'>
2025-01-01 20:09:29,163 - passlib.registry - DEBUG - registered 'bcrypt' handler: <class 'passlib.handlers.bcrypt.bcrypt'>
2025-01-01 20:09:29,179 - __main__ - ERROR - Database initialization error: Column expression, FROM clause, or other columns clause element expected, got <class '__main__.Faculty'>.
2025-01-01 20:09:29,179 - __main__ - ERROR - Application startup error: Column expression, FROM clause, or other columns clause element expected, got <class '__main__.Faculty'>.
2025-01-01 21:27:23,958 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): localhost:8000
2025-01-01 21:27:27,996 - __main__ - ERROR - API request error: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F802409150>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-01-01 21:27:27,998 - __main__ - ERROR - Unexpected error during login: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F802409150>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
